version: "3.9"

services:
  backend:
    build:
      context: ./Backend
    container_name: tirum-backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./Backend:/app
    expose:
      - "8000"
    environment:
      - DEBUG=1
    networks:
      - appnet

  frontend:
    build:
      context: ./tirumfrontend
      dockerfile: Dockerfile.prod
    container_name: tirum-frontend
    expose:
      - "3000"
    networks:
      - appnet

  nginx:
    build: ./nginx
    container_name: tirum-nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./Backend/static:/app/static  # <-- mount collected static files
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

